# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2011

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  # Categories: /categories/
  # About: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: springuper@gmail.com
  stack-overflow:
  twitter: https://twitter.com/springuper
  facebook:
  linkedin: https://www.linkedin.com/in/chun-shang-45a41241/
  google:
  github: https://github.com/springuper
  weibo:
  zhihu: https://www.zhihu.com/people/shang-chun
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-48551774-1
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: springuper
  repo: springuper.github.io
  client_id: 92e92021191ced09b547
  client_secret: 3b801ebb19243d851e7ccb3f7f7fc940f0536ef2
  admin_user: springuper
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language: zh-cn

# utterances
# Docs: https://utteranc.es/
# Tips: Make sure you have installed [utterances app](https://github.com/apps/utterances) in your repo
utterances:
  enable: true
  repo: springuper/springuper.github.io # Repository
  issueTerm: pathname # Blog post ↔️ issue mapping: pathname | url | title | og:title
  theme: github-light # Theme: github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  label: utterances # Issue label

# ===========================================
# Version
# ===========================================
version: 2.11.0
